import { IResource, ReturnCallback, SimpleCallback, Return2Callback, ResourceType } from '../IResource';
import { FSManager, FSPath } from '../../manager/FSManager';
import { LockKind } from '../lock/LockKind';
import { LockBag } from '../lock/LockBag';
import { Lock } from '../lock/Lock';
export declare abstract class StandardResource implements IResource {
    static sizeOfSubFiles(resource: IResource, callback: ReturnCallback<number>): void;
    properties: object;
    fsManager: FSManager;
    lockBag: LockBag;
    parent: IResource;
    dateCreation: number;
    dateLastModified: number;
    constructor(parent: IResource, fsManager: FSManager);
    isSame(resource: IResource, callback: ReturnCallback<boolean>): void;
    isOnTheSameFSWith(resource: IResource, callback: ReturnCallback<boolean>): void;
    getAvailableLocks(callback: ReturnCallback<LockKind[]>): void;
    getLocks(lockKind: LockKind, callback: ReturnCallback<Lock[]>): void;
    setLock(lock: Lock, callback: SimpleCallback): void;
    removeLock(uuid: string, owner: string, callback: ReturnCallback<boolean>): void;
    canRemoveLock(uuid: string, owner: string, callback: ReturnCallback<boolean>): void;
    canLock(lockKind: LockKind, callback: ReturnCallback<boolean>): void;
    setProperty(name: string, value: string, callback: SimpleCallback): void;
    getProperty(name: string, callback: ReturnCallback<string>): void;
    removeProperty(name: string, callback: SimpleCallback): void;
    getProperties(callback: ReturnCallback<object>): void;
    abstract create(callback: SimpleCallback): any;
    abstract delete(callback: SimpleCallback): any;
    abstract moveTo(to: FSPath, callback: Return2Callback<FSPath, FSPath>): any;
    abstract rename(newName: string, callback: Return2Callback<string, string>): any;
    abstract append(data: Int8Array, callback: SimpleCallback): any;
    abstract write(data: Int8Array, callback: SimpleCallback): any;
    abstract read(callback: ReturnCallback<Int8Array>): any;
    abstract mimeType(callback: ReturnCallback<string>): any;
    abstract size(callback: ReturnCallback<number>): any;
    creationDate(callback: ReturnCallback<number>): void;
    lastModifiedDate(callback: ReturnCallback<number>): void;
    abstract webName(callback: ReturnCallback<string>): any;
    abstract type(callback: ReturnCallback<ResourceType>): any;
    abstract addChild(resource: IResource, callback: SimpleCallback): any;
    abstract removeChild(resource: IResource, callback: SimpleCallback): any;
    abstract getChildren(callback: ReturnCallback<IResource[]>): any;
    protected updateLastModified(): void;
    protected removeFromParent(callback: SimpleCallback): void;
}
