import NotImplemented from './NotImplemented';
import Proppatch from './Proppatch';
import Propfind from './Propfind';
import Options from './Options';
import Delete from './Delete';
import Unlock from './Unlock';
import Mkcol from './Mkcol';
import Copy from './Copy';
import Lock from './Lock';
import Move from './Move';
import Head from './Head';
import Post from './Post';
import Get from './Get';
declare const _default: {
    NotImplemented: typeof NotImplemented;
    Proppatch: typeof Proppatch;
    Propfind: typeof Propfind;
    Options: typeof Options;
    Delete: typeof Delete;
    Unlock: typeof Unlock;
    Mkcol: typeof Mkcol;
    Copy: typeof Copy;
    Lock: typeof Lock;
    Move: typeof Move;
    Head: typeof Head;
    Post: typeof Post;
    Put: typeof Post;
    Get: typeof Get;
};
export default _default;
