/// <reference types="node" />
import { AvailableLocksInfo, CopyInfo, CreateInfo, CreationDateInfo, DeleteInfo, DisplayNameInfo, ETagInfo, LastModifiedDateInfo, LockManagerInfo, MimeTypeInfo, MoveInfo, OpenReadStreamInfo, OpenWriteStreamInfo, PropertyManagerInfo, ReadDirInfo, RenameInfo, SizeInfo, TypeInfo } from './ContextInfo';
import { Readable, Writable } from 'stream';
import { RequestContext } from '../../../server/v2/RequestContext';
import { BasicPrivilege } from '../../../user/v2/privilege/IPrivilegeManager';
import { LockKind } from '../../../resource/lock/LockKind';
import { Lock } from '../../../resource/lock/Lock';
import { Path } from '../Path';
import { ResourceType, SimpleCallback, Return2Callback, ReturnCallback, SubTree, OpenWriteStreamMode } from './CommonTypes';
import { ContextualFileSystem } from './ContextualFileSystem';
import { ILockManager } from './LockManager';
import { IPropertyManager } from './PropertyManager';
import { Resource } from './Resource';
import { ISerializableFileSystem, FileSystemSerializer } from './Serialization';
export declare abstract class FileSystem implements ISerializableFileSystem {
    private __serializer;
    constructor(serializer: FileSystemSerializer);
    serializer(): FileSystemSerializer;
    contextualize(ctx: RequestContext): ContextualFileSystem;
    resource(ctx: RequestContext, path: Path): Resource;
    fastExistCheckEx(ctx: RequestContext, path: Path, errorCallback: SimpleCallback, callback: () => void): void;
    fastExistCheckExReverse(ctx: RequestContext, path: Path, errorCallback: SimpleCallback, callback: () => void): void;
    protected fastExistCheck(ctx: RequestContext, path: Path, callback: (exists: boolean) => void): void;
    protected _fastExistCheck?(ctx: RequestContext, path: Path, callback: (exists: boolean) => void): void;
    create(ctx: RequestContext, path: Path, type: ResourceType, callback: SimpleCallback): void;
    create(ctx: RequestContext, path: Path, type: ResourceType, createIntermediates: boolean, callback: SimpleCallback): void;
    protected _create?(path: Path, ctx: CreateInfo, callback: SimpleCallback): void;
    etag(ctx: RequestContext, path: Path, callback: ReturnCallback<string>): void;
    protected _etag?(path: Path, ctx: ETagInfo, callback: ReturnCallback<string>): void;
    delete(ctx: RequestContext, path: Path, callback: SimpleCallback): void;
    delete(ctx: RequestContext, path: Path, depth: number, callback: SimpleCallback): void;
    protected _delete?(path: Path, ctx: DeleteInfo, callback: SimpleCallback): void;
    openWriteStream(ctx: RequestContext, path: Path, callback: Return2Callback<Writable, boolean>): void;
    openWriteStream(ctx: RequestContext, path: Path, estimatedSize: number, callback: Return2Callback<Writable, boolean>): void;
    openWriteStream(ctx: RequestContext, path: Path, targetSource: boolean, callback: Return2Callback<Writable, boolean>): void;
    openWriteStream(ctx: RequestContext, path: Path, targetSource: boolean, estimatedSize: number, callback: Return2Callback<Writable, boolean>): void;
    openWriteStream(ctx: RequestContext, path: Path, mode: OpenWriteStreamMode, callback: Return2Callback<Writable, boolean>): void;
    openWriteStream(ctx: RequestContext, path: Path, mode: OpenWriteStreamMode, estimatedSize: number, callback: Return2Callback<Writable, boolean>): void;
    openWriteStream(ctx: RequestContext, path: Path, mode: OpenWriteStreamMode, targetSource: boolean, callback: Return2Callback<Writable, boolean>): void;
    openWriteStream(ctx: RequestContext, path: Path, mode: OpenWriteStreamMode, targetSource: boolean, estimatedSize: number, callback: Return2Callback<Writable, boolean>): void;
    protected _openWriteStream?(path: Path, ctx: OpenWriteStreamInfo, callback: ReturnCallback<Writable>): void;
    openReadStream(ctx: RequestContext, path: Path, callback: ReturnCallback<Readable>): void;
    openReadStream(ctx: RequestContext, path: Path, estimatedSize: number, callback: ReturnCallback<Readable>): void;
    openReadStream(ctx: RequestContext, path: Path, targetSource: boolean, callback: ReturnCallback<Readable>): void;
    openReadStream(ctx: RequestContext, path: Path, targetSource: boolean, estimatedSize: number, callback: ReturnCallback<Readable>): void;
    protected _openReadStream?(path: Path, ctx: OpenReadStreamInfo, callback: ReturnCallback<Readable>): void;
    move(ctx: RequestContext, pathFrom: Path, pathTo: Path, callback: ReturnCallback<boolean>): void;
    move(ctx: RequestContext, pathFrom: Path, pathTo: Path, overwrite: boolean, callback: ReturnCallback<boolean>): void;
    protected _move?(pathFrom: Path, pathTo: Path, ctx: MoveInfo, callback: ReturnCallback<boolean>): void;
    copy(ctx: RequestContext, pathFrom: Path, pathTo: Path, callback: ReturnCallback<boolean>): void;
    copy(ctx: RequestContext, pathFrom: Path, pathTo: Path, depth: number, callback: ReturnCallback<boolean>): void;
    copy(ctx: RequestContext, pathFrom: Path, pathTo: Path, overwrite: boolean, callback: ReturnCallback<boolean>): void;
    copy(ctx: RequestContext, pathFrom: Path, pathTo: Path, overwrite: boolean, depth: number, callback: ReturnCallback<boolean>): void;
    protected _copy?(pathFrom: Path, pathTo: Path, ctx: CopyInfo, callback: ReturnCallback<boolean>): void;
    rename(ctx: RequestContext, pathFrom: Path, newName: string, callback: ReturnCallback<boolean>): void;
    rename(ctx: RequestContext, pathFrom: Path, newName: string, overwrite: boolean, callback: ReturnCallback<boolean>): void;
    protected _rename?(pathFrom: Path, newName: string, ctx: RenameInfo, callback: ReturnCallback<boolean>): void;
    mimeType(ctx: RequestContext, path: Path, callback: ReturnCallback<string>): void;
    mimeType(ctx: RequestContext, path: Path, targetSource: boolean, callback: ReturnCallback<string>): void;
    protected _mimeType?(path: Path, ctx: MimeTypeInfo, callback: ReturnCallback<string>): void;
    size(ctx: RequestContext, path: Path, callback: ReturnCallback<number>): void;
    size(ctx: RequestContext, path: Path, targetSource: boolean, callback: ReturnCallback<number>): void;
    protected _size?(path: Path, ctx: SizeInfo, callback: ReturnCallback<number>): void;
    availableLocks(ctx: RequestContext, path: Path, callback: ReturnCallback<LockKind[]>): void;
    protected _availableLocks?(path: Path, ctx: AvailableLocksInfo, callback: ReturnCallback<LockKind[]>): void;
    lockManager(ctx: RequestContext, path: Path, callback: ReturnCallback<ILockManager>): void;
    protected abstract _lockManager(path: Path, ctx: LockManagerInfo, callback: ReturnCallback<ILockManager>): void;
    propertyManager(ctx: RequestContext, path: Path, callback: ReturnCallback<IPropertyManager>): void;
    protected abstract _propertyManager(path: Path, ctx: PropertyManagerInfo, callback: ReturnCallback<IPropertyManager>): void;
    readDir(ctx: RequestContext, path: Path, callback: ReturnCallback<string[]>): void;
    readDir(ctx: RequestContext, path: Path, retrieveExternalFiles: boolean, callback: ReturnCallback<string[]>): void;
    protected _readDir?(path: Path, ctx: ReadDirInfo, callback: ReturnCallback<string[] | Path[]>): void;
    creationDate(ctx: RequestContext, path: Path, callback: ReturnCallback<number>): void;
    protected _creationDate?(path: Path, ctx: CreationDateInfo, callback: ReturnCallback<number>): void;
    lastModifiedDate(ctx: RequestContext, path: Path, callback: ReturnCallback<number>): void;
    protected _lastModifiedDate?(path: Path, ctx: LastModifiedDateInfo, callback: ReturnCallback<number>): void;
    webName(ctx: RequestContext, path: Path, callback: ReturnCallback<string>): void;
    displayName(ctx: RequestContext, path: Path, callback: ReturnCallback<string>): void;
    protected _displayName?(path: Path, ctx: DisplayNameInfo, callback: ReturnCallback<string>): void;
    type(ctx: RequestContext, path: Path, callback: ReturnCallback<ResourceType>): void;
    protected abstract _type(path: Path, ctx: TypeInfo, callback: ReturnCallback<ResourceType>): void;
    addSubTree(ctx: RequestContext, subTree: SubTree, callback: SimpleCallback): any;
    addSubTree(ctx: RequestContext, resourceType: ResourceType, callback: SimpleCallback): any;
    addSubTree(ctx: RequestContext, rootPath: Path, subTree: SubTree, callback: SimpleCallback): any;
    addSubTree(ctx: RequestContext, rootPath: Path, resourceType: ResourceType, callback: SimpleCallback): any;
    listDeepLocks(ctx: RequestContext, startPath: Path, callback: ReturnCallback<{
        [path: string]: Lock[];
    }>): any;
    listDeepLocks(ctx: RequestContext, startPath: Path, depth: number, callback: ReturnCallback<{
        [path: string]: Lock[];
    }>): any;
    getFullPath(ctx: RequestContext, callback: ReturnCallback<Path>): any;
    getFullPath(ctx: RequestContext, path: Path, callback: ReturnCallback<Path>): any;
    checkPrivilege(ctx: RequestContext, path: Path, privilege: BasicPrivilege, callback: ReturnCallback<boolean>): any;
    checkPrivilege(ctx: RequestContext, path: Path, privileges: BasicPrivilege[], callback: ReturnCallback<boolean>): any;
    checkPrivilege(ctx: RequestContext, path: Path, privilege: string, callback: ReturnCallback<boolean>): any;
    checkPrivilege(ctx: RequestContext, path: Path, privileges: string[], callback: ReturnCallback<boolean>): any;
    serialize(callback: ReturnCallback<any>): void;
}
